name: Build CI container

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/ci-containers/**"
      - "poetry.lock"
      - ".github/workflows/ci-container-build.yml"

jobs:
  build-ci-containers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build images
        run: make 2_28_${{ matrix.arch }}
        working-directory: .github/ci-containers
      - name: Push images
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin ghcr.io
          make push-2_28_${{ matrix.arch }}
          docker logout ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/ci-containers
