name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-13, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.13t"]
        include:
          - os: macos-13
            os-name: macos
            arch: x86_64
          - os: windows-latest
            os-name: windows
            arch: x86_64
          - os: macos-14
            os-name: macos
            arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip build poetry_core==2.1.3
      - name: Check version is coherent
        run: python .github/workflows/version_check.py pyproject.toml
      - name: Build
        # have to use -I here because otherwise python will pick up build.py because
        # python does very stupid things with its import path. -P would be the more
        # proper flag, but that doesn't exist until 3.11, so it's not generally
        # useful.
        run: python -Im build -w
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deqr-${{ matrix.os-name }}-${{ matrix.arch }}-py${{ matrix.python-version }}
          path: dist

  build-linux:
    defaults: { run: { working-directory: deqr-build } }
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/torque/deqr/linux-build:2_28_${{ matrix.arch }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          path: deqr-build
      - name: Check version is coherent
        run: |
          "${POETRY_PY}" .github/workflows/version_check.py pyproject.toml
      - name: Build
        run: |
          echo "::group::Build for Python 3.10"
          "${PY310}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.10 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"

          echo "::group::Build for Python 3.11"
          "${PY311}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.11 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"

          echo "::group::Build for Python 3.12"
          "${PY312}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.12 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"

          echo "::group::Build for Python 3.13"
          "${PY313}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.13 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"

          echo "::group::Build for Python 3.13t"
          "${PY313T}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.13t artifacts"
          git clean -fdxe dist
          echo "::endgroup::"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deqr-linux-${{ matrix.arch }}-multipy
          path: deqr-build/dist
      - name: Cleanup
        if: ${{ always() }}
        run: git clean -fdx
